"""Initial migration

Revision ID: 0ded749b91d7
Revises: 
Create Date: 2025-05-10 05:24:29.916869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ded749b91d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horas_estudio', sa.Float(), nullable=False),
    sa.Column('asistencia', sa.Float(), nullable=False),
    sa.Column('puntaje_examen', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
